print("")
name = input("enter the name of student")
age = input("enter the age of student")
phoneNumber = input("enter the phone number of student")
print("Name="+name , "age="+age , "phoneNumber="+phoneNumber)
